version: '2.2'
services:
  # the main ruby server
  inferno_program:
    image: onchealthit/inferno-program:latest
    volumes:
      # SITE-specific overlays
      - ./site-overlay/layout.erb:/var/www/inferno/lib/app/views/layout.erb
      - ./site-overlay/landing.erb:/var/www/inferno/lib/app/views/landing.erb
      # config file
      - ./inferno-config.yml:/var/www/inferno/config.yml
      # terminology data
      - ./bloom:/var/www/inferno/resources/terminology/validators/bloom
    # run the application
    working_dir: /var/www/inferno
    command: bundle exec rackup -o 0.0.0.0
    restart: unless-stopped
    mem_limit: 2000m
  inferno:
    image: onchealthit/inferno:latest
    volumes:
      # SITE-specific overlays
      - ./site-overlay/layout.erb:/var/www/inferno/lib/app/views/layout.erb
      - ./site-overlay/landing.erb:/var/www/inferno/lib/app/views/landing.erb
      # config file
      - ./community-config.yml:/var/www/inferno/config.yml
      # terminology data
      - ./bloom:/var/www/inferno/resources/terminology/validators/bloom
    # run the application
    working_dir: /var/www/inferno
    command: bin/run.sh
    depends_on:
      - bdt_service
      - community_validator_service
    restart: unless-stopped
    mem_limit: 2000m
  nginx_server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - /etc/ssl/certs/inferno:/etc/ssl/certs/inferno:ro
      # to use tls on localhost for development, comment out above line and uncomment below
      - ./nginx/development-certs:/etc/ssl/certs/inferno:ro
      - ./static-assets/:/var/www/inferno/public/
    ports:
      - "80:80"
      - "443:443"
    command: [nginx, '-g', 'daemon off;']
    links:
      - inferno:inferno
      - inferno_program:inferno_program
      - fhir_validator_app:fhir_validator_app
    restart: unless-stopped
    depends_on:
      - inferno
      - inferno_program
      - fhir_validator_app
      - community_validator_service
  bdt_service:
    image: infernocommunity/inferno-bdt-service
    mem_limit: 1000m
    restart: unless-stopped
  validator_service:
    image: infernocommunity/fhir-validator-service:v0.1.1
    mem_limit: 1500m
    restart: unless-stopped
  community_validator_service:
    image: infernocommunity/fhir-validator-service:latest
    mem_limit: 1500m
    restart: unless-stopped
  fhir_validator_app:
    image: infernocommunity/fhir-validator-app
    environment:
      EXTERNAL_VALIDATOR_URL: /validatorapi
      VALIDATOR_BASE_PATH: /validator
    mem_limit: 1000m
    restart: unless-stopped
    volumes:
      - /etc/ssl/certs/inferno:/etc/ssl/certs/inferno:ro
      # to use tls on localhost for development, comment out above line and uncomment below
      # - ./nginx/development-certs:/etc/ssl/certs/inferno:ro
  inferno_reference_server:
    image: infernocommunity/inferno-reference-server
    mem_limit: 1500m
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - fhir-pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  inferno_bulk_data_server:
    image: infernocommunity/bulk-data-server
    mem_limit: 1500m
    restart: unless-stopped

volumes:
  fhir-pgdata:
